/**
 * Post-call intelligence dossier for the technician, generated by AssemblyAI LLM Gateway
 * (the successor to LeMUR) over the real call transcript. No local fallback: if the
 * gateway is unavailable the caller gets an error, never a canned brief.
 */
import { structuredCompletion } from './assemblyai-llm.mjs';
import { MAX_TRANSCRIPT_CHARS } from './dictation.mjs';

const MOODS = ['calm', 'concerned', 'stressed', 'panicked'];

const DOSSIER_SYSTEM = [
  'You write a short pre-arrival brief for a solo plumbing, electrical, or HVAC technician from a phone call transcript.',
  'Base everything strictly on the transcript. Do not invent details, prices, brands, or equipment models that were not mentioned.',
  'pro_brief: 1-3 sentences on the problem and what was agreed.',
  'safety_guidance: safety advice that was actually given to the caller during the call, or null if none was given.',
  'parts_checklist: up to 5 parts or tools a technician would reasonably bring for the problem as described; empty if the problem is unclear.',
  'caller_mood_start / caller_mood_end: the caller\'s apparent mood at the start and end of the call, judged from their words.'
].join(' ');

export const DOSSIER_SCHEMA = {
  type: 'object',
  properties: {
    pro_brief: { type: 'string' },
    safety_guidance: { type: ['string', 'null'] },
    parts_checklist: { type: 'array', items: { type: 'string' } },
    caller_mood_start: { type: 'string', enum: MOODS },
    caller_mood_end: { type: 'string', enum: MOODS }
  },
  required: ['pro_brief', 'safety_guidance', 'parts_checklist', 'caller_mood_start', 'caller_mood_end'],
  additionalProperties: false
};

function text(value) {
  return typeof value === 'string' && value.trim() ? value.trim() : null;
}

export async function generateCallDossier(transcript, metadata = {}, options = {}) {
  const callText = String(transcript || '').trim();
  if (!callText) throw Object.assign(new Error('Call transcript is required.'), { statusCode: 422, code: 'transcript_required' });
  if (callText.length > MAX_TRANSCRIPT_CHARS) throw Object.assign(new Error(`Transcript is longer than ${MAX_TRANSCRIPT_CHARS} characters.`), { statusCode: 413, code: 'transcript_too_long' });

  const job = {
    customer_name: text(metadata.customer_name),
    service_type: text(metadata.service_type),
    scheduled_time: text(metadata.scheduled_time),
    address: text(metadata.address)
  };
  const known = Object.entries(job).filter(([, v]) => v).map(([k, v]) => `${k}: ${v}`).join('\n');

  const { data, model, requestId } = await structuredCompletion({
    system: DOSSIER_SYSTEM,
    user: `Call transcript:\n"""\n${callText}\n"""${known ? `\n\nBooked job details:\n${known}` : ''}`,
    schemaName: 'technician_dossier',
    schema: DOSSIER_SCHEMA,
    maxTokens: 700,
    fetchImpl: options.fetchImpl
  });

  const moodStart = MOODS.includes(data.caller_mood_start) ? data.caller_mood_start : null;
  const moodEnd = MOODS.includes(data.caller_mood_end) ? data.caller_mood_end : null;
  const when = job.scheduled_time ? ` for ${job.scheduled_time}` : '';
  const where = job.address ? ` at ${job.address}` : '';

  return {
    pro_brief: text(data.pro_brief) || '',
    safety_guidance: text(data.safety_guidance),
    parts_checklist: Array.isArray(data.parts_checklist) ? data.parts_checklist.map(String).slice(0, 5) : [],
    caller_mood: {
      start: moodStart,
      end: moodEnd,
      summary: moodStart && moodEnd ? `${moodStart} → ${moodEnd}` : null
    },
    customer_sms: `Hi${job.customer_name ? ` ${job.customer_name}` : ''}, your ${job.service_type || 'service'} appointment is confirmed${when}${where}. Reply to this text with any questions.`,
    pro_sms: `NEW JOB: ${[job.customer_name, job.service_type, job.scheduled_time, job.address].filter(Boolean).join(' | ')}`,
    model: `AssemblyAI LLM Gateway (${model})`,
    request_id: requestId
  };
}
